### ISSUE TITLE
ContractsGitLoader configuration through arquillian.xml fails

### ISSUE THREAD

**Issue by lbilger** [arquillian/arquillian-algeron#73]
##### Issue Overview

When I try to configure the `ContractsGitLoader` through arquillian.xml instead of annotation, I get a NullPointerException because `gitOperations` is not initialized.

##### Expected Behaviour

No NPE.

##### Current Behaviour

NPE occurs when `getContractsFolderFromGitRepo` tries to call methods on `gitOperations`.

##### Steps To Reproduce
1. Move configuration from `@ContractsGit` annotation to arquillian.xml, remove `@ContractsGit`.
2. Run test

##### Additional Information

`gitOperations` is only set in the `ContractsGitLoader(ContractsGit contractsGit)` constructor, but when configuring through arquillian.xml, the no-args constructor is used. The `configure` method is later called to set the configuration, but this method does not initialize the `gitOperations`. Probably only one line that needs to be added to `configure`.

**Comment by lordofthejars** [comment]
Good point, would you like to provide a PR? All Prs are more than welcome + it speed up the bug fixing so we can release a new version really quickly.

**Comment by lbilger** [comment]
Sure, I'll create a PR.

**Comment by lordofthejars** [comment]
great news.
