### ISSUE TITLE
Submit new release candidate

### ISSUE THREAD

**Issue by michbeck100** [arquillian/arquillian-algeron#91]
Is it possible to release a new rc version? As https://github.com/arquillian/arquillian-algeron/pull/89 is merged it would be great to have this on maven central.

**Comment by lordofthejars** [comment]
Yes it is possible, let me try to enter another PR which causes a bug in Windows and I'll do it.

**Comment by lordofthejars** [comment]
Hope I can do it today

**Comment by michbeck100** [comment]
Any news?

**Comment by lordofthejars** [comment]
I am going to try right now to see if I have time to do it before next
meeting :)

El dj., 20 de set. 2018 a les 16:08, Michael Kotten (<
notifications@github.com>) va escriure:

**Comment by lordofthejars** [comment]
Done in jboss nexus. In next 24 hours (or so) it should be sync with central repo.
